"""empty message

Revision ID: 114182b9b604
Revises: c6730f3b18b8
Create Date: 2025-12-20 00:29:14.285649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '114182b9b604'
down_revision: Union[str, Sequence[str], None] = 'c6730f3b18b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'theme_settings')
    op.drop_column('pages', 'title')
    op.drop_column('pages', 'published')
    op.drop_column('pages', 'description')
    op.drop_constraint(op.f('qrs_short_code_key'), 'qrs', type_='unique')
    op.drop_column('qrs', 'short_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qrs', sa.Column('short_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('qrs_short_code_key'), 'qrs', ['short_code'], postgresql_nulls_not_distinct=False)
    op.add_column('pages', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pages', sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('pages', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pages', sa.Column('theme_settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
