"""empty message

Revision ID: 63c122503c1a
Revises: eaacdf467be2
Create Date: 2025-11-10 13:17:07.424348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63c122503c1a'
down_revision: Union[str, Sequence[str], None] = 'eaacdf467be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'pages', ['name'])
    op.drop_column('qrs', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qrs', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pages', type_='unique')
    op.drop_column('pages', 'name')
    # ### end Alembic commands ###
