"""empty message

Revision ID: 72f792009bbc
Revises: 7d6dd1c47a86
Create Date: 2025-11-10 12:58:30.956655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f792009bbc'
down_revision: Union[str, Sequence[str], None] = '7d6dd1c47a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('qr_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('pages_QR_id_fkey'), 'pages', type_='foreignkey')
    op.create_foreign_key(None, 'pages', 'qrs', ['qr_id'], ['id'])
    op.drop_column('pages', 'QR_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('QR_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pages', type_='foreignkey')
    op.create_foreign_key(op.f('pages_QR_id_fkey'), 'pages', 'qrs', ['QR_id'], ['id'])
    op.drop_column('pages', 'qr_id')
    # ### end Alembic commands ###
