"""empty message

Revision ID: 84d3a5ca8e20
Revises: b040ee3fb025
Create Date: 2025-12-08 15:44:29.618519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d3a5ca8e20'
down_revision: Union[str, Sequence[str], None] = 'b040ee3fb025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qrs', sa.Column('src', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qrs', 'src')
    # ### end Alembic commands ###
