"""Поменял ссылку на возможно нулевую

Revision ID: a8b94ced1907
Revises: 63c122503c1a
Create Date: 2025-11-10 14:28:37.543483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b94ced1907'
down_revision: Union[str, Sequence[str], None] = '63c122503c1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qrs', 'link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('qrs_link_key'), 'qrs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('qrs_link_key'), 'qrs', ['link'], postgresql_nulls_not_distinct=False)
    op.alter_column('qrs', 'link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
