"""empty message

Revision ID: b040ee3fb025
Revises: 5affe74da324
Create Date: 2025-12-08 15:00:40.925500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b040ee3fb025'
down_revision: Union[str, Sequence[str], None] = '5affe74da324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pages_qr_id_fkey'), 'pages', type_='foreignkey')
    op.create_foreign_key(None, 'pages', 'qrs', ['qr_id'], ['id'], ondelete='SET NULL')
    op.add_column('qrs', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qrs', 'name')
    op.drop_constraint(None, 'pages', type_='foreignkey')
    op.create_foreign_key(op.f('pages_qr_id_fkey'), 'pages', 'qrs', ['qr_id'], ['id'], ondelete='SET DEFAULT')
    # ### end Alembic commands ###
