"""Проработал модели. Теперь в странице хранятся элементы через json

Revision ID: b6931f53b801
Revises: 126de78a39a5
Create Date: 2025-11-10 10:37:17.661658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6931f53b801'
down_revision: Union[str, Sequence[str], None] = '126de78a39a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('texts')
    op.drop_table('images')
    op.add_column('pages', sa.Column('background', sa.JSON(), nullable=False))
    op.add_column('pages', sa.Column('elements', sa.JSON(), nullable=False))
    op.add_column('qrs', sa.Column('name', sa.String(), nullable=False))
    op.add_column('qrs', sa.Column('description', sa.String(), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    op.drop_column('qrs', 'description')
    op.drop_column('qrs', 'name')
    op.drop_column('pages', 'elements')
    op.drop_column('pages', 'background')
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('images_page_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('images_pkey'))
    )
    op.create_table('texts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('texts_page_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('texts_pkey'))
    )
    # ### end Alembic commands ###
