"""empty message

Revision ID: c4403701cd1d
Revises: 72f792009bbc
Create Date: 2025-11-10 13:09:05.188082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4403701cd1d'
down_revision: Union[str, Sequence[str], None] = '72f792009bbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pages_qr_id_fkey'), 'pages', type_='foreignkey')
    op.create_foreign_key(None, 'pages', 'qrs', ['qr_id'], ['id'], ondelete='SETNULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pages', type_='foreignkey')
    op.create_foreign_key(op.f('pages_qr_id_fkey'), 'pages', 'qrs', ['qr_id'], ['id'])
    # ### end Alembic commands ###
