"""empty message

Revision ID: c6730f3b18b8
Revises: 1004b4b4a774
Create Date: 2025-12-20 00:17:59.349367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6730f3b18b8'
down_revision: Union[str, Sequence[str], None] = '1004b4b4a774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('title', sa.String(), nullable=True))
    op.add_column('pages', sa.Column('description', sa.String(), nullable=True))
    op.add_column('pages', sa.Column('published', sa.Boolean(), nullable=True))
    op.add_column('pages', sa.Column('theme_settings', sa.JSON(), nullable=True))
    op.add_column('qrs', sa.Column('short_code', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'qrs', ['short_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'qrs', type_='unique')
    op.drop_column('qrs', 'short_code')
    op.drop_column('pages', 'theme_settings')
    op.drop_column('pages', 'published')
    op.drop_column('pages', 'description')
    op.drop_column('pages', 'title')
    # ### end Alembic commands ###
