"""Страницы теперь приявзаны к пользователю

Revision ID: d9951cd63a41
Revises: 2f800e7183e1
Create Date: 2025-11-10 12:39:52.579318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9951cd63a41'
down_revision: Union[str, Sequence[str], None] = '2f800e7183e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('pages', 'QR_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('pages_QR_id_fkey'), 'pages', type_='foreignkey')
    op.create_foreign_key(None, 'pages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pages', 'qrs', ['QR_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pages', type_='foreignkey')
    op.drop_constraint(None, 'pages', type_='foreignkey')
    op.create_foreign_key(op.f('pages_QR_id_fkey'), 'pages', 'qrs', ['QR_id'], ['id'], ondelete='CASCADE')
    op.alter_column('pages', 'QR_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('pages', 'user_id')
    # ### end Alembic commands ###
