"""empty message

Revision ID: eaacdf467be2
Revises: c4403701cd1d
Create Date: 2025-11-10 13:09:50.174455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaacdf467be2'
down_revision: Union[str, Sequence[str], None] = 'c4403701cd1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pages_qr_id_fkey'), 'pages', type_='foreignkey')
    op.create_foreign_key(None, 'pages', 'qrs', ['qr_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pages', type_='foreignkey')
    op.create_foreign_key(op.f('pages_qr_id_fkey'), 'pages', 'qrs', ['qr_id'], ['id'])
    # ### end Alembic commands ###
