"""empty message

Revision ID: fbb834bdc333
Revises: a8b94ced1907
Create Date: 2025-12-08 01:54:50.013901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbb834bdc333'
down_revision: Union[str, Sequence[str], None] = 'a8b94ced1907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('files', sa.ARRAY(sa.String()), nullable=False))
    op.drop_constraint(op.f('pages_qr_id_fkey'), 'pages', type_='foreignkey')
    op.create_foreign_key(None, 'pages', 'qrs', ['qr_id'], ['id'], ondelete='SET DEFAULT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pages', type_='foreignkey')
    op.create_foreign_key(op.f('pages_qr_id_fkey'), 'pages', 'qrs', ['qr_id'], ['id'], ondelete='SET NULL')
    op.drop_column('pages', 'files')
    # ### end Alembic commands ###
